# Generated by Django 4.2.11 on 2026-05-10 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year', models.CharField(help_text='e.g. 2080/81 (Nepali fiscal year)', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('approved', 'Approved'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total budget in Nepali Rupees (NPR)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_allocation', models.DecimalField(decimal_places=2, default=50000, help_text='Minimum guaranteed allocation per school (NPR)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_per_school', models.DecimalField(decimal_places=2, default=500000, help_text='Maximum allocation any single school can receive (NPR)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_student_teacher', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_infrastructure', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_materials', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_geographic', models.FloatField(default=0.15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_socioeconomic', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('allocation_strategy', models.CharField(choices=[('priority', 'Priority-Based (Pure Greedy)'), ('equality', 'Equal Distribution'), ('hybrid', 'Hybrid (60% Priority + 40% Equal)')], default='priority', max_length=20)),
                ('target_provinces', models.JSONField(default=list, help_text='Province filter: [] means all provinces')),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('schools_covered', models.PositiveIntegerField(default=0)),
                ('utilization_rate', models.FloatField(default=0.0, help_text='Budget utilization % (0-100)')),
                ('gini_coefficient', models.FloatField(default=0.0, help_text='Fairness metric: 0=equal, 1=maximum inequality', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Cycle',
                'verbose_name_plural': 'Budget Cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_rank', models.PositiveIntegerField()),
                ('priority_score', models.FloatField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated (NPR)', max_digits=12)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount school needs (NPR)', max_digits=12)),
                ('allocation_pct', models.FloatField(default=0.0, help_text='% of total budget allocated to this school')),
                ('allocation_strategy', models.CharField(max_length=20)),
                ('fairness_score', models.FloatField(default=0.0, help_text='School-level fairness metric (0-1)')),
                ('allocation_tier', models.CharField(default='standard', help_text='minimum / standard / priority / maximum', max_length=20)),
                ('budget_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='allocation.budgetcycle')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='schools.school')),
            ],
            options={
                'ordering': ['priority_rank'],
                'unique_together': {('budget_cycle', 'school')},
            },
        ),
    ]
