# Generated by Django 4.2.11 on 2026-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationresult',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationresult',
            name='disbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed')], db_index=True, default='pending', max_length=20),
        ),
    ]
