# Generated by Django 4.2.11 on 2026-07-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_fiscal_year_budget_discretionary_grant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationresult',
            name='requested_amount',
        ),
    ]
