# Generated by Django 4.2.11 on 2026-05-10 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('emis', models.CharField(help_text='Education Management Information System code', max_length=20, unique=True)),
                ('province', models.CharField(choices=[('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('province1', 'Province No. 1 (Koshi)'), ('madhesh', 'Madhesh Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], db_index=True, max_length=30)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('ward_number', models.PositiveIntegerField(blank=True, null=True)),
                ('school_type', models.CharField(choices=[('primary', 'Primary (1-5)'), ('lower_secondary', 'Lower Secondary (1-8)'), ('secondary', 'Secondary (1-10)'), ('higher_secondary', 'Higher Secondary (1-12)')], default='primary', max_length=20)),
                ('is_rural', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('students', models.PositiveIntegerField(default=0)),
                ('teachers', models.PositiveIntegerField(default=1)),
                ('classrooms', models.PositiveIntegerField(default=1)),
                ('female_students', models.PositiveIntegerField(default=0)),
                ('female_teachers', models.PositiveIntegerField(default=0)),
                ('student_teacher_ratio', models.FloatField(default=0.0, help_text='Raw student-to-teacher ratio indicator (0-100, higher = worse)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('infrastructure_deficit', models.FloatField(default=0.0, help_text='Infrastructure deficit score (0-100, higher = worse)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('material_shortage', models.FloatField(default=0.0, help_text='Teaching material shortage index (0-100, higher = worse)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('geographic_difficulty', models.FloatField(default=0.0, help_text='Geographic accessibility difficulty (0-100, higher = more remote)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('socioeconomic_index', models.FloatField(default=0.0, help_text='Socioeconomic deprivation index (0-100, higher = more deprived)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority_score', models.FloatField(default=0.0, help_text='MCDA priority score (0-1, higher = higher priority)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('priority_rank', models.PositiveIntegerField(blank=True, help_text='Rank among all schools (1 = highest priority)', null=True)),
                ('teacher_demand', models.IntegerField(default=0, help_text='Additional teachers needed based on student count')),
                ('ranking_history', models.JSONField(default=list, help_text='Historical ranking records [{date, rank, score}]')),
                ('improvement_score', models.FloatField(default=0.0, help_text='Improvement trend (+ve = improving, -ve = declining)')),
                ('last_ranking_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority_rank', 'name'],
                'indexes': [models.Index(fields=['province', 'district'], name='schools_sch_provinc_04fc92_idx'), models.Index(fields=['priority_rank'], name='schools_sch_priorit_10b27f_idx'), models.Index(fields=['priority_score'], name='schools_sch_priorit_98712c_idx')],
            },
        ),
    ]
