# Generated by Django 4.2.11 on 2026-05-23 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0004_school_constraints_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_teacher_ratio', models.FloatField()),
                ('infrastructure_deficit', models.FloatField()),
                ('material_shortage', models.FloatField()),
                ('geographic_difficulty', models.FloatField()),
                ('socioeconomic_index', models.FloatField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rank', models.IntegerField()),
                ('current_score', models.FloatField()),
                ('reason', models.TextField()),
                ('supporting_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='schools_sch_provinc_ad82f1_idx',
            old_name='school_prov_rank_idx',
        ),
        migrations.RenameIndex(
            model_name='school',
            new_name='schools_sch_distric_f6f780_idx',
            old_name='school_dist_rural_idx',
        ),
        migrations.AddField(
            model_name='rankingappeal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankingappeal',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='schools.school'),
        ),
        migrations.AddField(
            model_name='rankingappeal',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataverificationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataverificationrequest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='schools.school'),
        ),
        migrations.AddField(
            model_name='dataverificationrequest',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
