# Generated by Django 4.2.11 on 2026-05-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_2a1328_idx',
            old_name='audit_action_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_e8be02_idx',
            old_name='audit_user_ts_idx',
        ),
    ]
